package py.com.tipcsa.eva.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class ImgFullScreenView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Window window;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Embedded img;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ImgFullScreenView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	

	public Embedded getImg() {
		return img;
	}



	public void setImg(Embedded img) {
		this.img = img;
	}
    
	


	public VerticalLayout getMainLayout() {
		return mainLayout;
	}



	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// img
		img = new Embedded();
		
		img.setWidth("100.0%");
		img.setHeight("100.0%");
		img.setSource(new ThemeResource("img/component/embedded_icon.png"));
		img.setType(1);
		img.setMimeType("image/png");
		mainLayout.addComponent(img);
		
		return mainLayout;
	}



	public Window getWindow() {
		return window;
	}



	public void setWindow(Window window) {
		this.window = window;
	}

}
