package py.com.tipcsa.eva.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.LoginForm.LoginEvent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.declarative.Design;

import py.com.tipcsa.eva.event.EventBus;

import py.com.tipcsa.eva.jpa.JpaUsuarios;
import py.com.tipcsa.eva.util.JpaUtil;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginView extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout loginLayout;
	@AutoGenerated
	private LoginForm loginAysa;
	private Window window;

	private JpaUsuarios jpaUsuario = new JpaUsuarios(JpaUtil.getEntityManagerFactory());
	public LoginView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		loginAysa.setUsernameCaption("Funcionario");
		loginAysa.setPasswordCaption("Constraseña");
		
		loginAysa.addLoginListener(event -> loggear(event));
		
	}
	private void loggear(LoginEvent evento) {
	
		
		String pass;
		String user;
		boolean ingresar;
		
		pass = evento.getLoginParameter("password").toString();
		user = evento.getLoginParameter("username").toString();
		
		if (pass == "") {
			Notification.show("Debe ingresar la contraseña", Notification.Type.ERROR_MESSAGE);
			return;
		}
		
		if (user == "") {
			Notification.show("Debe ingresar el usuario", Notification.Type.ERROR_MESSAGE);
			return;
		}
		
		ingresar = jpaUsuario.login(user, pass);
		if (ingresar) {
			
		/*	//Notification.show("Adelante");
			FuncionariosView funView = new FuncionariosView();
			Window ventana = new Window("Funcionarios", funView);
			ventana.center();
			ventana.setResizable(true);
			ventana.setModal(true);
			UI.getCurrent().addWindow(ventana);*/
			EventBus.post(new py.com.tipcsa.eva.event.LoginEvent(jpaUsuario.findUsuario(1)));
			//EventBus.post(new py.com.tipcsa.eva.event.LoginEvent());
			
			
			
		}else {
			Notification.show("Usuario o contraseña incorrectos", Notification.Type.ERROR_MESSAGE);
		}
		
		
		
		
		
		
		
	}
	
	
	public void setWindow(Window window){
		this.window = window;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// loginLayout
		loginLayout = buildLoginLayout();
		mainLayout.addComponent(loginLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildLoginLayout() {
		// common part: create layout
		loginLayout = new VerticalLayout();
		//loginLayout.setImmediate(false);
		loginLayout.setWidth("100.0%");
		loginLayout.setHeight("100.0%");
		loginLayout.setMargin(false);
		
		// loginAysa
		loginAysa = new LoginForm();
		loginAysa.setStyleName("v-loginform");
		//loginAysa.setImmediate(false);
		loginAysa.setWidth("-1px");
		loginAysa.setHeight("-1px");
		loginLayout.addComponent(loginAysa);
		loginLayout.setComponentAlignment(loginAysa, new Alignment(48));
		
		return loginLayout;
	}

	
	
	
	
	
	
	
	
	
	
}
