package py.com.tipcsa.eva.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

import py.com.tipcsa.eva.EvaUI;
import py.com.tipcsa.eva.util.ViewConfig;




@ViewConfig(uri = "", displayName = "Principal")
public class PrincipalView extends CustomComponent implements View {
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout datosLayout;
	@AutoGenerated
	private HorizontalLayout botonLayout;
	@AutoGenerated
	private Button btn3;
	@AutoGenerated
	private Button btn2;
	@AutoGenerated
	private Button btn1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private Button btn4 ;
	private Button btn5;
	private Button btn6;
	private Button btn7;
	
	public PrincipalView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		btn4 = new Button();
		btn5 = new Button();
		btn6 = new Button();
		btn7 = new Button();
		
	
		btn1.setCaption("Vacaciones");
		btn2.setCaption("Funcionarios");
		btn3.setCaption("Alta Funcionario");
		btn4.setCaption("Feriados");
		btn5.setCaption("Solicitud Vacaciones");
		btn6.setCaption("Aprobación de Vacaciones");
		btn7.setCaption("Modificaciones de Departamento");
		
		
		
		
		
		btn1.addClickListener(event -> {
			EvaUI.getCurrent().getNavigator().navigateTo("vacacion");
		});
		
		btn2.addClickListener(event -> EvaUI.getCurrent().getNavigator().navigateTo("funcionario"));
		
		btn3.addClickListener(event -> EvaUI.getCurrent().getNavigator().navigateTo("altaFuncionario"));
		
		
		botonLayout.addComponents(btn4, btn5, btn6, btn7);
		
	}
	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// datosLayout
		datosLayout = buildDatosLayout();
		mainLayout.addComponent(datosLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildDatosLayout() {
		// common part: create layout
		datosLayout = new VerticalLayout();
		//datosLayout.setImmediate(false);
		datosLayout.setWidth("100.0%");
		datosLayout.setHeight("100.0%");
		datosLayout.setMargin(false);
		
		// botonLayout
		botonLayout = buildBotonLayout();
		datosLayout.addComponent(botonLayout);
		datosLayout.setComponentAlignment(botonLayout, new Alignment(48));
		
		return datosLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildBotonLayout() {
		// common part: create layout
		botonLayout = new HorizontalLayout();
		//botonLayout.setImmediate(false);
		botonLayout.setWidth("-1px");
		botonLayout.setHeight("-1px");
		botonLayout.setMargin(false);
		
		// btn1
		btn1 = new Button();
		btn1.setCaption("Button");
		//btn1.setImmediate(true);
		btn1.setWidth("-1px");
		btn1.setHeight("-1px");
		botonLayout.addComponent(btn1);
		
		// btn2
		btn2 = new Button();
		btn2.setCaption("Button");
		//btn2.setImmediate(true);
		btn2.setWidth("-1px");
		btn2.setHeight("-1px");
		botonLayout.addComponent(btn2);
		
		// btn3
		btn3 = new Button();
		btn3.setCaption("Button");
		//btn3.setImmediate(true);
		btn3.setWidth("-1px");
		btn3.setHeight("-1px");
		botonLayout.addComponent(btn3);
		
		return botonLayout;
	}
	
	
	
	
	
	
	
	

}
